# 数据源
spring:
  datasource:
    url: jdbc:mysql://rm-8vb0y48ka75163mv9so.mysql.zhangbei.rds.aliyuncs.com:3306/blog
    ?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: zlc01
    password: 123!@#qwe

