# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp162pgo0uzr9u0hcmo.mysql.rds.aliyuncs.com:3306/blog?serverTimezone=Asia/Shanghai
    username: rly01
    password: RLY@@@111

# 日志

