# 数据源
spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    username: root
    #    password: 123456
    #    url: jdbc:mysql://47.98.125.78:3306/blog?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    #    url: jdbc:p6spy:mysql://rm-bp162pgo0uzr9u0hcmo.mysql.rds.aliyuncs.com:3306/blog?serverTimezone=Asia/Shanghai
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: admin
