# 数据源
spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://rm-8vb0y48ka75163mv9so.mysql.zhangbei.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: zlc01
    password: 123!@#qwe


#配置评论头像
comment.avatar: /image/avatar.png

